//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libary.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LitteratureCopy
    {
        public LitteratureCopy()
        {
            this.LitteratureLoans = new HashSet<LitteratureLoan>();
        }
    
        public int ID { get; set; }
        public int StatusID { get; set; }
        public int LitteratureID { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<System.DateTime> PurchaseYear { get; set; }
    
        public virtual Litterature Litterature { get; set; }
        public virtual ICollection<LitteratureLoan> LitteratureLoans { get; set; }
        public virtual LitteratureCopyStatu LitteratureCopyStatu { get; set; }
    }
}
