//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libary.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Litterature
    {
        public Litterature()
        {
            this.LitteratureCopies = new HashSet<LitteratureCopy>();
        }
    
        public int ID { get; set; }
        public int AuthorID { get; set; }
        public string ISBN { get; set; }
        public string Title { get; set; }
        public string Genre { get; set; }
        public string Language { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<LitteratureCopy> LitteratureCopies { get; set; }
    }
}
