//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libary.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LitteratureLoan
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int LitteratureCopyID { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public System.DateTime Returndate { get; set; }
        public bool LoanReturned { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual LitteratureCopy LitteratureCopy { get; set; }
    }
}
