//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Libary.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class vNumberOfCopiesAvailable
    {
        public string BookTitle { get; set; }
        public string ISBN { get; set; }
        public int CopyID { get; set; }
        public string Availability { get; set; }
        public int ID { get; set; }
    }
}
